### ISSUE TITLE
The apcu-gui license is not compatible with GPL

### ISSUE THREAD

**Issue by mudrd8mz** [moodleuulm/moodle-tool_apcu#1]
The included lib/apcu-gui's license is the PHP License, version 3.01.

According to https://www.gnu.org/licenses/license-list.en.html#PHP-3.01, this license is not compatible with the GNU GPL. As a result, a GPL'ed code (the moodle plugin) cannot be distributed with that library included in one package. As a policy, Moodle HQ does not provide such packages via the plugins directory hosting platform.

Possible solutions to this legal policy blocker is to let administrator themselves to download and deploy the apcu-gui library.

**Comment by mudrd8mz** [comment]
Relevant sources:

* http://gplv3.fsf.org/wiki/index.php/PHP_license%2C_version_3.01
* https://www.gnu.org/licenses/gpl-faq.en.html#WhatDoesCompatMean

**Comment by abias** [comment]
Hi @mudrd8mz ,

thank you very much for reviewing this plugin and for highlighting this issue. I have to admit that I was not aware of this incompatibility, but I fully respect it.

I would go with your proposal to let administrators themselves download and deploy the apcu-gui library into the plugin. This will be as easy as running a single wget / curl command on the Moodle server and can be documented in the plugin README file as well as within the plugin admin page itself (and be shown if the library is not there).

However, I am also thinking about Moodle installations where admins do not have access to the webserver filesystem but where the admin is allowed to install plugins via the web-based plugin installer.

As long as we don't have any Composer support for Moodle plugins, I could write a db/install.php feature which will let Moodle download the library from github and place it on disk during the plugin installation.

Will this be acceptable for the moodle plugins repository or will this also be considered as "incompatible" or even blamed as "the plugin is sideloading potentially evil code from unknown sources"?

**Comment by mudrd8mz** [comment]
The fact that the plugin would be downloading and deploying the code is not a problem. The issue with the plugins directory is that it cannot host and distribute GPL'ed ZIP files with included PHP licensed software (or better GPL'ed ZIP fike with any non-compatible content). In all these cases, we recommend maintainers to make it so that it is the admin who combines the things together - as they are the end users and do not distribute the result further.

Whether it is done automatically in db/install.php or manually via some admin interface, is a detail. You will probably want to have the manual installation support anyway - for cases when the automatic one fails (e.g. insufficient write access, connectivity issues etc).

**Comment by abias** [comment]
Hey @mudrd8mz ,

I finally had the time to implement the downloading and deploying code which I proposed above. It was committed with https://github.com/moodleuulm/moodle-tool_apcu/commit/8913237789d9b08913cc997696dc97e5c9713b05.

I will now create a new release for moodle.org/plugins to let you finish the approval.

Cheers,
Alex
